# BT APP configuration file

# Enable BT On by default
# valid value : true, false
BtEnableByDefault=false

# Local device BT name
BtLocalDeviceName=MDM_Fluoride

# User Interface is needed
# valid value : true, false
UserInteractionNeeded=true
